# Generated by Django 3.0.2 on 2020-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0003_auto_20180610_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfilter',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, the filter will be available for all users'),
        ),
    ]
